var         = @{ ("<" ~ &ASCII_ALPHA_UPPER) ~ ASCII_ALPHA_UPPER ~ ASCII_ALPHA* ~ ('0'..'9')* ~ ">" }

fact       = _{ SOI ~ rfact ~ EOI }

rfact        = { (pred ~ n ~ fib | pred ~ n) }

n           = { decimal }
fib           = { decimal }

pred        = @{ "fib" | "q" }

decimal        = _{ v_decimal | var }

v_decimal = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT*)? }

WHITESPACE  = { (" " | "\t" | NEWLINE)+ }
