knowledge   = { (sentence ~ ".")+ }

sentence    = _{ rule | fact }

rule        = { antecedents+ ~ consequents }

antecedents = { factset ~ "→" }
consequents = { factset }

factset     = _{ fact ~ ("∧" ~ fact)* }

var         = @{ "<" ~ "__"? ~ "X" ~ ('0'..'9')+ ~ ">" }

fact        = { name ~ pred ~ name }

pred        = @{ "∈" | "⊆" }

v_name      = @{ ASCII_ALPHANUMERIC+ }

name        = _{ v_name | var }

WHITESPACE  = { " " | "\t" | "\r" | "\n" }