conditions       = _{ SOI ~ rconditions ~ EOI }

rconditions  = { v_expr ~ ((";"|"∧") ~ v_expr)* }

var         = @{ ("<" ~ &ASCII_ALPHA_UPPER) ~ ASCII_ALPHA_UPPER ~ ASCII_ALPHA* ~ ('0'..'9')* ~ ">" }

v_expr = { term ~ pred ~ term }

term = _{ v_decimal | var }

pred = {
    "==" | "!=" | "<=" | ">=" | "<" | ">"
}

v_decimal = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT*)? }

WHITESPACE = _{ (" " | "\t" | NEWLINE)+ }
