
conditions  = { v_expr ~ ((";"|"∧") ~ v_expr)* }

var         = @{ "<" ~ "__"? ~ "X" ~ ('0'..'9')+ ~ ">" }

v_expr = {
      monadicExpr
    | dyadicExpr
}

monadicExpr = { monadicPred ~ term }

dyadicExpr = { term ~ dyadicPred ~ term }

term = _{ v_decimal | var | "(" ~ v_expr ~ ")" }

monadicPred = {
    "not"
}

dyadicPred = {
    "==" | "<" | ">" | "or"
}

v_decimal = @{ "_"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* }

WHITESPACE = _{ (" " | "\t" | NEWLINE)+ }
